services:
  - type: web
    name: beritakarya-api
    env: node
    plan: free
    region: singapore
    buildCommand: pnpm install && pnpm build --filter=@beritakarya/api
    startCommand: pnpm --filter @beritakarya/api run db:migrate:deploy && pnpm --filter @beritakarya/api start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: API_URL
        sync: false
      - key: NEXT_PUBLIC_API_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: RESET_SECRET
        generateValue: true
      - key: CSRF_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        sync: false
      - key: COOKIE_DOMAIN
        sync: false
      - key: EMAIL_ENABLED
        value: "false"
      - key: OPENAI_API_KEY
        sync: false
      - key: S3_ENDPOINT
        sync: false
      - key: S3_REGION
        value: "ap-southeast-1"
      - key: S3_ACCESS_KEY
        sync: false
      - key: S3_SECRET_KEY
        sync: false
      - key: S3_FORCE_PATH_STYLE
        value: "true"
      - key: S3_BUCKET
        value: "kyc"
