export { LegalPageHeader } from './LegalPageHeader'
export { LegalPageIntro } from './LegalPageIntro'
export { LegalDocumentBody } from './LegalDocumentBody'
export { LegalStandardPage } from './LegalStandardPage'
export type { LegalStandardPageProps } from './LegalStandardPage'
export { legalProseClassName } from './legalStyles'
