user nginx;
worker_processes 1;
error_log /var/log/nginx/error.log warn;

events { worker_connections 512; }

http {
  include      /etc/nginx/mime.types;
  default_type application/octet-stream;

  log_format main '$remote_addr "$request" $status rt=$request_time';
  access_log /var/log/nginx/access.log main;
  server_tokens off;

  # ── Staging server (HTTP) ──────────────────────────────────
  server {
    listen 80;
    server_name *.staging.beritakarya.co staging.beritakarya.co;

    client_max_body_size 15M;

    location /api/ {
      proxy_pass       http://api:3001;
      proxy_set_header Host            $host;
      proxy_set_header X-Real-IP       $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      set $subdomain "";
      if ($host ~* "^([^.]+)\.staging\.beritakarya\.co$") {
        set $subdomain $1;
      }
      proxy_set_header X-Site-ID $subdomain;
    }

    location /uploads/ {
      proxy_pass http://api:3001;
    }

    location / {
      proxy_pass         http://web:3000;
      proxy_set_header   Host              $host;
      proxy_set_header   X-Real-IP         $remote_addr;
      proxy_http_version 1.1;
      proxy_set_header   Upgrade    $http_upgrade;
      proxy_set_header   Connection "upgrade";
    }
  }
}
